### ISSUE TITLE
Please add Leisure Suit Larry 6 CD

### ISSUE THREAD

**Issue by deckarep** [EricOakford/SCI-Decompilation-Archive#1]
Hello,

I am hoping to see LSL6CD at some point...just curious if it will be added or if anything is preventing it from being added from a technical standpoint?

These are great resources cheers!

**Comment by EricOakford** [comment]
The issue is that the game's interpreter has a version stamp check, which causes it to abort if the resource file is altered in any way. This is true for both the VGA (SCI1.1) and SVGA (SCI2.1) versions. However, I may be able to do a decompilation of the floppy disk version, as that has no version stamp check.

**Comment by deckarep** [comment]
Hey thanks for the reply!

Follow up question: would it still be worthwhile to get a decompile of this game even if it’s not playable as in just for reference purposes? Or does the issue you mention prevent the decompile process from working?

The floppies version would be a good fallback.

Thanks again!

**Comment by ZvikaZ** [comment]
Eric, I personally enjoy reading your code, for debugging and hacking, and I don't really care whether it runs with Dosbox.

Therefore, I think that if you can, there is value in adding games that have problems like LSL6 (maybe you can commen in Readme about such issues)

Anyway, thanks again for sharing this amazing work!

**Comment by deckarep** [comment]
One side question: I have manually decompiled some games using my own copy of the games. I have noticed that my output from SCICompanion is not as rich as what's in this github repo. 

Is that simply because many identifiers are lost in the bytecode file format? Where did this repo get many of the identifiers for local vars, global, external refs, etc?

Is it just a matter of methodical reverse engineering the code to identify good variable names? If that is the case that is some hard, impressive work!

**Comment by EricOakford** [comment]
Yes, it was just me going script by script, identifying various things as I went along. With the system scripts and globals, I just typically use the original source scripts, which helps significantly.
Think of it as remastering a classic Disney movie. The people who worked on the remasters had to go through each and every frame to make sure they were cleaned up and presentable for retail release. If you ever watched a featurette on Disney's film restoration process, you can see that the raw scans of the original negatives (which Disney wisely had scanned in 4K) are rather dirty and unpolished. That is much like a raw decompilation of an SCI game.

On a side note, I found that the SVGA version of LSL6 does not appear to have a version-stamp check! So it looks like I can use that as the basis for the game's decompilation, and adhere with my standard of using the newest versions of the games.

**Comment by deckarep** [comment]
@EricOakford  - are you using SciCompanion to decompile the games? If you don’t mind, which version are you using? 

Since the original one doesn’t seem maintained any further I’m trying to find out which one is recommended.

**Comment by EricOakford** [comment]
I've been using Kawa's build. That seems to be the best option.

Also, I've finally managed to put together an (incomplete) decompilation of LSL6 SVGA. I may continue work on this, but I'm frazzled right now.
