### ISSUE TITLE
Adding quick instructions how to use the files

### ISSUE THREAD

**Issue by lwcorp** [EricOakford/SCI-Decompilation-Archive#17]
The official debug modes (if such exist) involved using a software like SCI Resource Viewer to extract certain internal files and then put them in the game's folder.

But how can one use this great archive here? For example, if the game is qfg3, what should one do with the files on this archive in order to get debug mode in the game?

**Comment by lwcorp** [comment]
Until anyone answers, fortunately https://tcrf.net/Quest_for_Glory_III:_Wages_of_War provides direct download links to the **actual** debug files.

**Comment by ZvikaZ** [comment]
Your question is actually few different questions. I will try to answer two of them:

> how does one rebuild/recompile a game with these files

The best tool that we have now for this is SCI Companion. Its (great) documentation is at http://scicompanion.com/. However, the download link in the official site is for quite old version. I recommend using Kawa's updated version - https://helmet.kafuka.org/sci/SCICompanion.zip.

With SCICompanion you can decompile an original Sierra game (just point to its `resource.map`), modify whatever you like, and then recompile. The changes can be written back to `resource.*` files, or exported as single patch files, that can be added to the original game directory.

The decompiler is amazing, but not perfect. It has few bugs and quirks. That's where this repo comes. Erikoakford used SCICompanion's decompiler, and then fixed bugs, renamed some identifiers with generic/wrong names, and verified that the recompiled game is completeable.

> what should one do with the files on this archive

One should fire up SCICompanion, decompile, and then replace the decompiled files with the files from this repo, recompile, verify that it's still working. If it does - further changes can be done.

A great place to ask questions, learn more, and get more links to interesting Sierra stuff - https://sciprogramming.com/community/

**Comment by lwcorp** [comment]
Thanks! But in this game's case, the debug files are just two - 18.scr and 18.hep - where are they in https://github.com/EricOakford/SCI-Decompilation-Archive/tree/master/qfg3 and how does one compile only them without touching anything else? This is exactly what someone in the aforementioned link managed to do.

**Comment by Doomlazer** [comment]
You don't need this archive to export 18.scr and 18.hep for the debugger. Just open a retail version of QfG3 with SCICompanion, switch to the scripts tab, then right-click on script 18 and click "Export script as patch". Switch to the hep tab and export hep 18 with right-click as well. Put the export patch files in your QfG3 game folder.

**Comment by Doomlazer** [comment]
Here is the process: 

Make a copy of your QFG3 game folder, so you aren't changing your original game files. 

Copy the QFG3 src folder and game.ini from the EO's archive into that new QFG3 folder: https://github.com/EricOakford/SCI-Decompilation-Archive/tree/master/qfg3

Open the qfg3 resource.map with SCICompanion as ZvikaZ described above. In SCICompanion, switch to the Scripts tab. Notice there is no script numbered 018.

Use Script > Compile All, which will produce a bunch of errors, but there should now be a script called "debug" numbered 018.

Right-click debug and select "Export as patch file", which should be named 18.src.

Switch the Heaps tab in SCICompanion. Right-click heap n018 and select "Export as patch file", which should be named 18.hep.

Move the resulting 18.src and 18.hep into your original game folder and run QFG normally. Debug should appear on launch.

**Comment by lwcorp** [comment]
Wow, thanks for the detailed instructions.
Thankfully the aforementioned wiki site exported these files [in October 15th 2021](https://tcrf.net/index.php?title=Quest_for_Glory_III:_Wages_of_War&diff=1097531&oldid=435881) while the latest Kawa's updated version is from October 23th 2021. So I hope there weren't changes that justify redoing this process.

**Comment by Doomlazer** [comment]
The version of SCICompanion should not make a difference. It would be changes to the "debug" script number 18 in this archive that would require rebuilding the 18.scr and 18.hep patches. 

If bugs are found in the QfG3 debugger, they would need to be fixed here and recompiled, but otherwise the version on that wiki you linked is pretty close to final.

**Comment by Doomlazer** [comment]
The nightly builds, if you don't want to compile yourself, are found here: https://github.com/Kawa-oneechan/SCICompanion/releases

**Comment by lwcorp** [comment]
> The best tool that we have now for this is SCI Companion...However, the download link in the official site is for quite old version. I recommend using Kawa's updated version.

Which new features/bug fixes does Kawa's fork have, BTW?
