### ISSUE TITLE
KQ4 rm83 bug Lolotte's Cell

### ISSUE THREAD

**Issue by MrMalm** [EricOakford/SCI-Decompilation-Archive#3]
In kq4/SRC/rm83.sc there is a typo on line 123

`((Said '/skeleton,[') (Print 83 1))`

should be

`((Said '/skeleton') (Print 83 1))`

The extra .[ causes the game to throw an error message when looking at any specific item in the room, i.e. "Look wall".

**Comment by MrMalm** [comment]
Also, a few lines down:

`((Said 'call,help,,') (Print 83 16))`

Should be 

`((Said 'call,help') (Print 83 16))`

**Comment by EricOakford** [comment]
It seems like some said specs did not decompile properly. I had similar issues with LSL2. This has been fixed.
