### ISSUE TITLE
KQ4 dwarf_mine

### ISSUE THREAD

**Issue by Doomlazer** [EricOakford/SCI-Decompilation-Archive#4]
In KQ4 rm55.sc  changing

`(if (== newRoomNumber 28) ((ScriptID DWARF_HOUSE) keep: 0))`

to

`(if (== newRoomNumber 28) ((ScriptID DWARF_MINE) keep: 0))`

stops the music when exiting the mine. 

Also, in rm56.sc changing 

`(self setRegions: DWARF_HOUSE)`

to 

`(self setRegions: DWARF_MINE)`

prevents "out of heap space" crashes when entering fisherman or dwarf houses after Rosella has entered the 2nd mine screen rm56.

Edit:
rm44.sc has some said spec errors.

`((Said '>,ignite,create,begin/fire')(Print 44 9))`
and
`((Said '/)') (Print 44 13))`
are both causing errors. 

Thank you!

**Comment by EricOakford** [comment]
Ah, yes! I made some mistakes, and overlooked decompilation bugs. That's fixed.
