### ISSUE TITLE
KQ4 Lamp/Note

### ISSUE THREAD

**Issue by Doomlazer** [EricOakford/SCI-Decompilation-Archive#5]
Sorry for being a nuisance, but I started working on a KQ4 mod before I realized the decompile wasn't completable. Now that I've invested a bunch of time in the project I'd like to see if we can work through some lingering issues that prevent the player from finishing the game.

Currently there are a bunch of said spec errors in the caves behind the waterfall. While I can deal with those, turning on the lamp doesn't seem possible because of some spec errors in main.sc. Unfortunately, I haven't learned assembly yet, and I'm struggling to find a workaround for igniting the lamp. 

Also, when reading the Note from the bottle in the whale, nothing seems to happen. I think this might also be related to the asm code in main.sc. It's trivial, but I'd like to be able to read the note in my mod if possible. 

With the heap space crashes fixed, I think getting the lamp to turn on would make this game close to completable! Your work on these decompiles has been extremely valuable in trying to mod KQ4. Thank you for the effort - it's appreciated!

**Comment by Doomlazer** [comment]
The lamp will turn off and on after editing Main.sc from
`lofsa    '>,ignite,(turn<on)`
to
`lofsa    'ignite,(turn<on)`

Previously when I tried editing this I was restoring from a save file which loaded the old code - doh!

**Comment by EricOakford** [comment]
I was able to fix the said spec error relating to the lamp, but the note isn't related to any said specs.

This game and LSL2 are the only two games I know of that have issues with decompiling said specs, possibly because they were the very first SCI games.

**Comment by Doomlazer** [comment]
Ok, thank you. I'll look into the note later. That's interesting it's only those two games. KQ4 certainly has a lot of them. I think there is still some said spec issue with turning the lamp on while in darkness, but I need to test more. 

I did fix two game breaking bugs though: 

In rm78.sc jump script (3 the first two ego commands both should be changed to:
`(ego setMotion: JumpTo [jumpArea local1] [jumpArea (+ local1 1)] setLoop: 2 cel: 255 setCycle: EndLoop self)`
This fixes rosella from jumping to the wrong location after entering the 2nd swamp screen.

The second is an out of heap space error when entering the giant's house after having visited rm70.  In rm70.sc 
the second `(cascade2` should be `cascade3`

Finally, this isn't game breaking, but in rm15.sc under frogActions script (11 the golden ball is moved back to the player, but is not disposed: so it remains visible. I think vanilla KQ4 leaves the ball on the ground to be picked up if the player wants it.

**Comment by Doomlazer** [comment]
The heap space crash in the throne room ended up being from the custom inventory items I added. It's just an extremely tight squeeze I guess with all the scripts in that room, but it shouldn't be a problem on your end. 

The final crash I encountered is in the cutscene after giving the talisman to Genesta. It transitions outside to room 690. 

`(= wave1 (Prop new:))`
`(= wave2 (Prop new:))`

needs to be added in the rm690.sc init method right above `(wave1`

That should make the game playable to completion! There are still a ton of said spec errors to find and some other issues as well. I notice the audio will occasionally break and doors sometimes visually disappear, but my goal here was to get it playable, so feel free to close this issue now. 

Thank you!

**Comment by EricOakford** [comment]
Yeah, the swamp jumps are a decompiler goof related to arrays.

Since I've just fixed the bugs in question, it's closing time at last.

**Comment by Doomlazer** [comment]
I'll keep an eye out for that update!

**Comment by Doomlazer** [comment]
Since I mentioned this in the original issue, reading the note can be fixed in main.sc:

code_0f1b:
			pushi    1
			pushi    2000
			call     IsHeapFree,  2
			bnt      code_0f36
			pushi    #cue
			pushi    0
			pushi    2
			pushi    306
			`pushi    2  ;was 1. prevented reading whale note`
			callk    ScriptID,  4
			send     4
			jmp      code_1bc6
