### ISSUE TITLE
KQ4 whale tongue

### ISSUE THREAD

**Issue by Doomlazer** [EricOakford/SCI-Decompilation-Archive#6]
There is a strange bug in the whale's mouth rm44.sc. It's almost never encountered because of how unforgiving  the tongue is, but you might want to fix it anyway. 

If Rosella is standing on top of the tongue and tries to climb down she will softlock unless she hits the green control color before the water. The player will normally almost always hit the green, but if you adjust the background pic to make climbing really easy the bug becomes apparent. 

In the inWhale  script doit method there is a check for ego script 0, but a few lines down when it calls `(slide changestate: 1)` it doesn't set a script on Rosella. This causes the game to keep checking the control colors during the fall and breaks stuff.

I fixed this by adding `(ego setScript: slide)` before changing the state.

**Comment by EricOakford** [comment]
I've gotten the fix in, as well as that room's said spec errors. They'll be up soon.
